--[[
MSP_VehicleOptimizeGraph — W900 蒙皮車門模型把 FBX 的輔助節點也當骨頭，每台車每幀白算

【上游】W900 Semi-Truck（rSemiTruck，Workshop 3409472393，核對版本為 upstream.json 的 acked_time_updated）。
upstream.json 有登記，Workshop 更新時 Action 會開 issue。

【缺陷】
客戶端對每台已載入的車，每幀都對每個非 static 零件模型完整重算一次骨架（BaseVehicle.postupdate
42.21.0 :3770-3781 → updateAnimationPlayer :3898-3904，無距離／可見／靜止閘門）。骨架是整個 FBX：
找不到 `Dummy01`／`VehicleSkeleton` 時整個場景節點都算骨頭，找到時取其最上層祖先的整棵子樹
（ImportedSkeleton.java:56-75）。assimp 匯入 FBX 會替有 pre-rotation 的節點補 `$AssimpFbx$` 輔助節點，
這些輔助節點和純 mesh 節點因此也算進骨頭：W900 車頭每個門／引擎蓋 49 根（真正的骨架 6 根），
半聯結拖車 28 根、箱型車後門 30 根。成本＝每幀 Update 次數 × 骨頭數。
KI5 系列同樣能套用（每個 FBX 只多 2 根），實測每台只省 0～4 µs，不值得背幾十個上游的重核負擔，所以不收；
要擴大時把上游登記進 upstream.json（patches 列本檔）再跑 `scripts/check_optimize_graph.py --write`。

【修法】
在任何車輛模型匯入前，對白名單裡的模型腳本呼叫 `ModelScript:Load`，body 只寫
`postProcess = +OPTIMIZE_GRAPH`：`Load` 不 reset，只設 body 寫到的欄位（ModelScript.java:54-109，
postProcess 在 :90-91）；`ModelManager.getLoadedModel` 把它傳進 `loadModelInternal`（ModelManager.java:1394-1400），
`FileTask_LoadMesh.loadFBX` 依它增加 assimp 步驟（FileTask_LoadMesh.java:79-90、151-163），把沒有動畫、
不被蒙皮引用的節點摺掉。被摺的節點在 PZ 本來就是單位矩陣（bindPose 只覆寫 aiBone，ImportedSkeleton.java:114-156；
無 keyframe 的骨頭 AnimationTrack.java:929-931 回單位矩陣），畫面不變。
白名單由 `scripts/check_optimize_graph.py` 產生：用遊戲本體的 jassimp 匯入同一個 FBX 開／不開這個步驟，
逐 mesh 比頂點、mesh 節點矩陣、骨頭 offset、動畫與動畫節點階層，全等才收。執行期再守三件事：模型腳本存在、
仍非 static、mesh 仍是白名單記的那一個；有一項不符就不動它。

時機：本檔在 client Lua 載入時執行。Core.ResetLua 先 `ScriptManager.Load` 再載 Lua（Core.java:3931、3949；
連線時由 ConnectToServerState.java:125 觸發，在進世界之前；開遊戲時 GameWindow.java:203、993），而車輛零件模型
只在車輛建立時才匯入（BaseVehicle.java:868-872 → ModelManager.addVehicle :1130-1139；ModelManager.create :139-181
不預載車輛模型），所以本檔一定早於第一台車。例外：mesh asset 以路徑為鍵、先載先贏（AssetManager.java:51-67），
Model 快取在整個遊戲程序內保留（ModelManager.Reset 只清 slot，IngameState.java:899）；同一次開遊戲裡若先在別的伺服器
／單機或除錯車輛編輯器匯入過同一個 mesh，這次設定不生效（不報錯、畫面照舊），重開遊戲後生效。

【為什麼不改上游】
W900 沒有轉載授權；改 FBX（加 VehicleSkeleton 根節點）要散布修改過的模型檔。本補丁不複製任何上游檔案內容，
只在本服客戶端改匯入參數。

【軟依賴】
不 require rSemiTruck。白名單裡的模型腳本一個都不存在時什麼都不做（不註冊事件、不印 log）。

【上游更新時要重核】
跑 `python scripts/check_optimize_graph.py`；FAIL 時確認差異再 `--write` 重產白名單。
]]

local PREFIX = "[MinidoracatServerPatchFor42][VehicleOptimizeGraph]"
local BODY = " { postProcess = +OPTIMIZE_GRAPH, }" -- 結尾逗號必要：ScriptParser 只在逗號處切值

-- BEGIN GENERATED by scripts/check_optimize_graph.py; do not edit by hand
local LIST = {
    -- 3409472393 rSemiTruck (17)
    ["Rotators.ContainerDoorR"] = "vehicles/ContainerTrailer|Container_DoorR",
    ["Rotators.ContainerDoorRTrailer"] = "vehicles/ContainerTrailer|Container_DoorR_Trailer",
    ["Rotators.ContainerDoorRTrailer_Blue"] = "vehicles/ContainerTrailer|Container_DoorR_Trailer",
    ["Rotators.ContainerDoorRTrailer_Green"] = "vehicles/ContainerTrailer|Container_DoorR_Trailer",
    ["Rotators.ContainerDoorRTrailer_Red"] = "vehicles/ContainerTrailer|Container_DoorR_Trailer",
    ["Rotators.ContainerDoorRTrailer_Yellow"] = "vehicles/ContainerTrailer|Container_DoorR_Trailer",
    ["Rotators.ContainerDoorR_Blue"] = "vehicles/ContainerTrailer|Container_DoorR",
    ["Rotators.ContainerDoorR_Green"] = "vehicles/ContainerTrailer|Container_DoorR",
    ["Rotators.ContainerDoorR_Red"] = "vehicles/ContainerTrailer|Container_DoorR",
    ["Rotators.ContainerDoorR_Yellow"] = "vehicles/ContainerTrailer|Container_DoorR",
    ["Rotators.SemiTruckBoxTrunk"] = "vehicles/vehicles_SemiTruckBox_Body|Trunk_mesh",
    ["Rotators.SemiTruckHood"] = "vehicles/vehicles_SemiTruck_Body|Hood_mesh",
    ["Rotators.SemiTruckTrunkLeft"] = "vehicles/vehicles_SemiTruck_Body|TrunkLeft_mesh",
    ["Rotators.SemiTruckTrunkRight"] = "vehicles/vehicles_SemiTruck_Body|TrunkRight_mesh",
    ["Rotators.TrailerCisternTrunk"] = "vehicles/trailers_Cistern_Body|Toolbox_mesh",
    ["Rotators.TrailerVanToolbox"] = "vehicles/trailers_Van_Body|Toolbox_mesh",
    ["Rotators.TrailerVanTrunk"] = "vehicles/trailers_Van_Body|Trunk_mesh",
}
-- END GENERATED

local applied = {} -- 已處理過的 ModelScript；同一個 Lua 環境重複呼叫不再 Load

-- 回傳 已設定數、白名單內但上游已改（static 或 mesh 不同）而跳過的數
local function apply()
    local sm = getScriptManager and getScriptManager()
    if not sm then return 0, 0 end
    local done, changed = 0, 0
    for full, mesh in pairs(LIST) do
        local ms = sm:getModelScript(full)
        if ms and not applied[ms] then
            applied[ms] = true
            local cur = ms:getMeshName()
            if ms:isStatic() or not cur or string.lower(cur) ~= string.lower(mesh) then
                changed = changed + 1
            elseif pcall(function() ms:Load(ms:getName(), "model " .. ms:getName() .. BODY) end) then
                done = done + 1
            else
                changed = changed + 1
            end
        end
    end
    return done, changed
end

local done, changed = apply()
if done + changed > 0 then
    print(PREFIX .. " +OPTIMIZE_GRAPH set on " .. done .. " vehicle model scripts"
        .. (changed > 0 and ("; " .. changed .. " skipped (changed upstream, re-run scripts/check_optimize_graph.py)") or ""))
end

-- 離線測試用（scripts/test_vehicle_optimize_graph.lua）；遊戲內不會有人引用
MSP_VehicleOptimizeGraph = { apply = apply, LIST = LIST }
